[package]
name = "highflowey/simplehitbox"
version = "1.0.35"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
bridgenet2 = "ffrostflame/bridgenet2@1.0.0"
squash = "data-oriented-house/squash@1.1.6"
signal = "sleitnick/signal@1.5.0"
